### ISSUE TITLE
Send out event to play the next song when the current one finishes

### ISSUE THREAD

**Issue by davepagurek** [pahgawk/Pluto#16]
@andrew749 is this doable with mplayer?

**Comment by andrew749** [comment]
@pahgawk  maybe listen for an exit code from the command line

**Comment by andrew749** [comment]
liks that all i can think of

**Comment by davepagurek** [comment]
Right now we get an exit code immediately from spawning the mplayer process, we'd need to somehow also listen to the process we make. I think we may be able to get its pid though and listen to that, I'll look into it.
