### ISSUE TITLE
Allow signin to happen from a third party device

### ISSUE THREAD

**Issue by davepagurek** [pahgawk/Pluto#17]
If we're tapping an nfc thing on a phone on the wall, the phone has to be able to sign in each user. Right now this isn't possible since sign in only happens based on the IP of the person logging in. What I'm thinking of doing:
- Give each user a username or hash or something unchanging to put on the nfc tag
- Give each user an array of registered IPs so devices still work
- Allow sign-in both by IP or by username/hash/thing

Do we want to add passwords or just trust each other?

**Comment by andrew749** [comment]
I guess just trust
