### ISSUE TITLE
Video surveillance from webcam with livestream

### ISSUE THREAD

**Issue by andrew749** [pahgawk/Pluto#2]

**Comment by rtsun95** [comment]
No.

**Comment by andrew749** [comment]
yes

**Comment by davepagurek** [comment]
We'd need an rpi with a camera, do we have one that supports that?

**Comment by yucombinator** [comment]
I do have one, and maybe we can have a camera to monitor the door or the backyard. Having a camera recording the inside of the house seems very Orwellian to me.

**Comment by andrew749** [comment]
Lol it was just a joke.
