### ISSUE TITLE
Adding music playback

### ISSUE THREAD

**Issue by andrew749** [pahgawk/Pluto#3]
Title says it all. Make a plugin to allow modules to access some music playback framework.

**Comment by davepagurek** [comment]
I'm thinking we get a list of users' preferred artists and then use a Songza or Spotify api to get a playlist and then send that to Muzic

**Comment by davepagurek** [comment]
http://stackoverflow.com/questions/21899074/spotify-app-api-creating-a-player-of-top-tracks-from-an-artist

**Comment by andrew749** [comment]
We should probably let everyone know that this is almost done.
