### ISSUE TITLE
Check if downloaded song is just a preview

### ISSUE THREAD

**Issue by davepagurek** [pahgawk/Pluto#6]
We keep getting these 30-second previews. Ways we can check if we need a redownload:
- If we can check the length of the song (most direct route)
- If we can check the filesize. This isn't a direct indicator, but we may want to check this anyway. We need the finest goods for our ears.
  - We may be able to check this _before_ downloading. I mean, Chrome does it when you download a file, right?

**Comment by andrew749** [comment]
actually curl also recgonized how big the file is but i don't think you can actually see how large the song file is before downloading it. Unless it is stored in metadata.

**Comment by davepagurek** [comment]
Looks like if we use the npm request package to download files, we can use the `content-length` header: http://stackoverflow.com/questions/12740659/downloading-images-with-node-js

**Comment by andrew749** [comment]
merged https://github.com/pahgawk/Pluto/pull/13
