### ISSUE TITLE
Give real time feedback with song downloading.

### ISSUE THREAD

**Issue by andrew749** [pahgawk/Pluto#7]

**Comment by davepagurek** [comment]
websockets maybe?

**Comment by andrew749** [comment]
wed have to awk the curl to get the data and maybe websockets to communicate from the curl reading script.

**Comment by davepagurek** [comment]
also can the raspberry pi handle hosting a node server and also something like socket.io?

**Comment by andrew749** [comment]
lol probably no

**Comment by yucombinator** [comment]
maybe if we get a better board like the beaglebone black?

**Comment by andrew749** [comment]
i have an old computer im gonna bring, maybe we can use that?
Just not sure how much more life it has left in it.

**Comment by davepagurek** [comment]
in the mean time, sketchy way to do it without websockets would be to have an `<iframe>` with the loading message in it, and the page the iframe links to reloads itself every ~5 seconds using js. ghetto but it would work

**Comment by andrew749** [comment]
can a raspi even handle a web browser?

**Comment by davepagurek** [comment]
Well we'd be loading this on our phones mostly, hence the need for me to make this more responsive. Like our TV will be in the basement, right? so I'm thinking it might not even make sense to have it connected to the tv at all, we can just use our laptops if we really want

**Comment by andrew749** [comment]
wait i thought the tv was gonna act like a scrum board and be in the main level

**Comment by davepagurek** [comment]
we should ask in slack

**Comment by andrew749** [comment]
merged https://github.com/pahgawk/Pluto/pull/13
