### ISSUE TITLE
News ticker on main page

### ISSUE THREAD

**Issue by andrew749** [pahgawk/Pluto#8]

**Comment by andrew749** [comment]
currently in branch news_ticker

**Comment by yucombinator** [comment]
Where do we draw the news source from?

**Comment by andrew749** [comment]
google news. Maybe in the future we can create a group feedly and integrate with that.

**Comment by davepagurek** [comment]
what format is that, rss?

**Comment by andrew749** [comment]
right now google news is json. Like I said the data parsing is done, we just need to connect it to the ui.

**Comment by andrew749** [comment]
![screen shot 2015-08-24 at 7 19 50 pm](https://cloud.githubusercontent.com/assets/2242730/9455065/5a1a4f3e-4a95-11e5-8dba-8f3ceb1c483c.png)

**Comment by andrew749** [comment]
early prototype for news

**Comment by andrew749** [comment]
https://github.com/pahgawk/Pluto/pull/11

**Comment by andrew749** [comment]
merged https://github.com/pahgawk/Pluto/pull/11
