### ISSUE TITLE
Communal memo board

### ISSUE THREAD

**Issue by kong-artist** [pahgawk/Pluto#9]
Would be cool to have somewhere we can post notes? Sort of like a communal Google Keep... Close this issue if you guys would rather use a shared Google Keep note instead (this is what we did during co-op term for groceries)

**Comment by davepagurek** [comment]
lol nah we need to go 100% homegrown, plus this one shouldn't be too hard to make. I'll give it a shot tomorrow, tonight I'm busy

**Comment by andrew749** [comment]
trello

**Comment by andrew749** [comment]
Can we just embed a trello iframe

**Comment by andrew749** [comment]
http://jsfiddle.net/danlec/hmQJP/

**Comment by davepagurek** [comment]
That works for me.

**Comment by andrew749** [comment]
so i did an iframe but im not sure where to put it

**Comment by davepagurek** [comment]
We probably want to put it on its own page and link to it from the main page, similar to what we do with the music page.

**Comment by andrew749** [comment]
OK so I guess I'll do that tonight.

**Comment by andrew749** [comment]
https://github.com/pahgawk/Pluto/pull/24
